global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/prometheus_rules.yml

scrape_configs:
  - job_name: spam-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8080
