apiVersion: v1
kind: Service
metadata:
  name: spam-api-svc
  labels:
    app: spam-api
spec:
  type: NodePort
  selector:
    app: spam-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
